services:
  api:
    ports:
      - "3000:3000"
    environment:
      API_KEY: "superdev"
      SWAGGER_ON: "1"
      HOST: "0.0.0.0"
      PORT: "3000"

      MINIO_ENDPOINT: "minio"
      MINIO_PORT: "9000"
      MINIO_USE_SSL: "false"
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_BUCKET: "evidencias"
      MINIO_PUBLIC_BASE: "http://127.0.0.1:9000/evidencias/"
      PDF_FORCE_PUBLIC_URL: "true"
      MAIN_WAREHOUSE_CODE: "CENTRAL"
# DATABASE_URL: "postgresql://ispuser:isp123@db:5432/ispdb"
