--
-- PostgreSQL database dump
--

\restrict qF8r6I7WjGOS9ug9wSsXa84gerQXM4mm1fq8iXiHIF7YMTuvXZSjhSJmWLwTcej

-- Dumped from database version 14.19
-- Dumped by pg_dump version 14.19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: almacenes; Type: TABLE; Schema: public; Owner: ispuser
--

CREATE TABLE public.almacenes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tipo text DEFAULT 'principal'::text NOT NULL,
    tecnico_id integer,
    codigo text NOT NULL,
    nombre text,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT almacenes_tipo_check CHECK ((tipo = ANY (ARRAY['principal'::text, 'tecnico'::text])))
);


ALTER TABLE public.almacenes OWNER TO ispuser;

--
-- Name: movimientos; Type: TABLE; Schema: public; Owner: ispuser
--

CREATE TABLE public.movimientos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    idempotency_key text,
    tipo text NOT NULL,
    almacen_origen_id uuid,
    almacen_destino_id uuid,
    material_id integer NOT NULL,
    cantidad integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    motivo text,
    ref_externa text,
    evidencia_key text,
    usuario_op_id integer,
    fecha timestamp with time zone DEFAULT now() NOT NULL,
    from_almacen_id uuid,
    to_almacen_id uuid,
    tecnico_id integer,
    nota text,
    CONSTRAINT movimientos_cantidad_check CHECK ((cantidad > 0)),
    CONSTRAINT movimientos_tipo_check CHECK ((tipo = ANY (ARRAY['ingreso'::text, 'egreso'::text, 'ajuste'::text, 'traslado'::text])))
);


ALTER TABLE public.movimientos OWNER TO ispuser;

--
-- Name: materiales; Type: TABLE; Schema: public; Owner: ispuser
--

CREATE TABLE public.materiales (
    id integer NOT NULL,
    codigo text,
    nombre text NOT NULL,
    precio numeric(12,2) DEFAULT 0 NOT NULL,
    unidad text,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.materiales OWNER TO ispuser;

--
-- Name: materiales_id_seq; Type: SEQUENCE; Schema: public; Owner: ispuser
--

ALTER TABLE public.materiales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materiales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_almacen; Type: TABLE; Schema: public; Owner: ispuser
--

CREATE TABLE public.stock_almacen (
    almacen_id uuid NOT NULL,
    material_id integer NOT NULL,
    cantidad integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT ck_stock_no_negativo CHECK ((cantidad >= 0)),
    CONSTRAINT stock_almacen_cantidad_nonneg CHECK ((cantidad >= 0))
);


ALTER TABLE public.stock_almacen OWNER TO ispuser;

--
-- Name: almacenes almacenes_pkey; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.almacenes
    ADD CONSTRAINT almacenes_pkey PRIMARY KEY (id);


--
-- Name: materiales materiales_codigo_key; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.materiales
    ADD CONSTRAINT materiales_codigo_key UNIQUE (codigo);


--
-- Name: materiales materiales_pkey; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.materiales
    ADD CONSTRAINT materiales_pkey PRIMARY KEY (id);


--
-- Name: movimientos movimientos_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_idempotency_key_key UNIQUE (idempotency_key);


--
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id);


--
-- Name: stock_almacen stock_almacen_pkey; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.stock_almacen
    ADD CONSTRAINT stock_almacen_pkey PRIMARY KEY (almacen_id, material_id);


--
-- Name: almacenes uq_almacenes_codigo; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.almacenes
    ADD CONSTRAINT uq_almacenes_codigo UNIQUE (codigo);


--
-- Name: materiales uq_materiales_codigo; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.materiales
    ADD CONSTRAINT uq_materiales_codigo UNIQUE (codigo);


--
-- Name: stock_almacen uq_stock_almacen_almacen_material; Type: CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.stock_almacen
    ADD CONSTRAINT uq_stock_almacen_almacen_material UNIQUE (almacen_id, material_id);


--
-- Name: idx_movimientos_created; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_movimientos_created ON public.movimientos USING btree (created_at);


--
-- Name: idx_movimientos_destino; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_movimientos_destino ON public.movimientos USING btree (almacen_destino_id);


--
-- Name: idx_movimientos_material; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_movimientos_material ON public.movimientos USING btree (material_id);


--
-- Name: idx_movimientos_origen; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_movimientos_origen ON public.movimientos USING btree (almacen_origen_id);


--
-- Name: idx_movs_destino; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_movs_destino ON public.movimientos USING btree (almacen_destino_id) WHERE (almacen_destino_id IS NOT NULL);


--
-- Name: idx_movs_origen; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_movs_origen ON public.movimientos USING btree (almacen_origen_id) WHERE (almacen_origen_id IS NOT NULL);


--
-- Name: idx_movs_tipo_mat_fecha; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_movs_tipo_mat_fecha ON public.movimientos USING btree (tipo, material_id, fecha DESC);


--
-- Name: idx_stock_almacen_mat; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_stock_almacen_mat ON public.stock_almacen USING btree (almacen_id, material_id);


--
-- Name: idx_stock_almacen_material; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_stock_almacen_material ON public.stock_almacen USING btree (material_id);


--
-- Name: idx_stock_almacen_updated; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX idx_stock_almacen_updated ON public.stock_almacen USING btree (updated_at);


--
-- Name: ix_mov_fecha; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_mov_fecha ON public.movimientos USING btree (fecha DESC);


--
-- Name: ix_mov_from_almacen; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_mov_from_almacen ON public.movimientos USING btree (from_almacen_id);


--
-- Name: ix_mov_material; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_mov_material ON public.movimientos USING btree (material_id);


--
-- Name: ix_mov_tipo; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_mov_tipo ON public.movimientos USING btree (tipo);


--
-- Name: ix_mov_to_almacen; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_mov_to_almacen ON public.movimientos USING btree (to_almacen_id);


--
-- Name: ix_movs_dest_mat_created; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_movs_dest_mat_created ON public.movimientos USING btree (almacen_destino_id, material_id, created_at DESC);


--
-- Name: ix_movs_orig_mat_created; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_movs_orig_mat_created ON public.movimientos USING btree (almacen_origen_id, material_id, created_at DESC);


--
-- Name: ix_stock_almacen_almacen; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_stock_almacen_almacen ON public.stock_almacen USING btree (almacen_id);


--
-- Name: ix_stock_almacen_mat; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE INDEX ix_stock_almacen_mat ON public.stock_almacen USING btree (material_id);


--
-- Name: ux_stock_almacen; Type: INDEX; Schema: public; Owner: ispuser
--

CREATE UNIQUE INDEX ux_stock_almacen ON public.stock_almacen USING btree (almacen_id, material_id);


--
-- Name: almacenes almacenes_tecnico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.almacenes
    ADD CONSTRAINT almacenes_tecnico_id_fkey FOREIGN KEY (tecnico_id) REFERENCES public.tecnicos(id);


--
-- Name: movimientos movimientos_from_almacen_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_from_almacen_id_fkey FOREIGN KEY (from_almacen_id) REFERENCES public.almacenes(id) ON DELETE SET NULL;


--
-- Name: movimientos movimientos_tecnico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_tecnico_id_fkey FOREIGN KEY (tecnico_id) REFERENCES public.tecnicos(id) ON DELETE SET NULL;


--
-- Name: movimientos movimientos_to_almacen_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_to_almacen_id_fkey FOREIGN KEY (to_almacen_id) REFERENCES public.almacenes(id) ON DELETE SET NULL;


--
-- Name: stock_almacen stock_almacen_almacen_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.stock_almacen
    ADD CONSTRAINT stock_almacen_almacen_id_fkey FOREIGN KEY (almacen_id) REFERENCES public.almacenes(id) ON DELETE CASCADE;


--
-- Name: stock_almacen stock_almacen_material_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ispuser
--

ALTER TABLE ONLY public.stock_almacen
    ADD CONSTRAINT stock_almacen_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materiales(id);


--
-- PostgreSQL database dump complete
--

\unrestrict qF8r6I7WjGOS9ug9wSsXa84gerQXM4mm1fq8iXiHIF7YMTuvXZSjhSJmWLwTcej

