-- Asegura default en materiales.id según su tipo actual,
-- respetando si ya es IDENTITY o si ya tiene nextval(...)
DO $$
DECLARE
  col_type    text;
  col_default text;
  is_ident    text;
BEGIN
  SELECT data_type, column_default, is_identity
  INTO col_type, col_default, is_ident
  FROM information_schema.columns
  WHERE table_schema='public'
    AND table_name='materiales'
    AND column_name='id';

  IF col_type IS NULL THEN
    RAISE NOTICE 'No existe materiales.id; se omite.';
    RETURN;
  END IF;

  IF is_ident = 'YES' THEN
    RAISE NOTICE 'materiales.id ya es IDENTITY; no se modifica.';
    RETURN;
  END IF;

  IF col_default IS NOT NULL THEN
    RAISE NOTICE 'materiales.id ya tiene DEFAULT (%); no se modifica.', col_default;
    RETURN;
  END IF;

  IF col_type IN ('integer','bigint') THEN
    EXECUTE 'ALTER TABLE materiales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
    RAISE NOTICE 'materiales.id ahora es IDENTITY.';
  ELSIF col_type = 'uuid' THEN
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    EXECUTE 'ALTER TABLE materiales ALTER COLUMN id SET DEFAULT gen_random_uuid()';
    RAISE NOTICE 'materiales.id ahora tiene DEFAULT gen_random_uuid().';
  ELSE
    RAISE NOTICE 'Tipo no soportado (%) para materiales.id; no se modifica el default.', col_type;
  END IF;
END$$;
