-- migration_20251002_inventario_core.sql
-- Núcleo de inventario: crea entidades base en orden seguro.

BEGIN;

-- Usamos esquema público explícitamente
SET search_path TO public;

-- Extensiones necesarias
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- para gen_random_uuid()

/* =========================
   1) Tabla: materiales
   ========================= */
CREATE TABLE IF NOT EXISTS materiales (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    TEXT NOT NULL UNIQUE
);

/* =========================
   2) Tabla: almacenes
   ========================= */
CREATE TABLE IF NOT EXISTS almacenes (
  id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre    TEXT NOT NULL UNIQUE
);

/* ======================================
   3) Tipo ENUM para movimientos.tipo
   ====================================== */
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'movimiento_tipo') THEN
    CREATE TYPE movimiento_tipo AS ENUM ('ingreso','egreso','ajuste','transferencia');
  END IF;
END$$;

/* =========================
   4) Tabla: movimientos
   ========================= */
CREATE TABLE IF NOT EXISTS movimientos (
  id                 BIGSERIAL PRIMARY KEY,
  tipo               movimiento_tipo NOT NULL,
  almacen_origen_id  UUID REFERENCES almacenes(id) ON DELETE SET NULL,
  almacen_destino_id UUID REFERENCES almacenes(id) ON DELETE SET NULL,
  material_id        INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
  cantidad           NUMERIC(14,2) NOT NULL CHECK (cantidad >= 0),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Índices útiles para consultas por material/almacén/fecha
CREATE INDEX IF NOT EXISTS idx_movimientos_material ON movimientos(material_id);
CREATE INDEX IF NOT EXISTS idx_movimientos_origen   ON movimientos(almacen_origen_id);
CREATE INDEX IF NOT EXISTS idx_movimientos_destino  ON movimientos(almacen_destino_id);
CREATE INDEX IF NOT EXISTS idx_movimientos_created  ON movimientos(created_at);

/* ===========================================
   5) Tabla: stock_almacen  (depende de 1 y 2)
   =========================================== */
CREATE TABLE IF NOT EXISTS stock_almacen (
  id           BIGSERIAL PRIMARY KEY,
  almacen_id   UUID NOT NULL REFERENCES almacenes(id) ON DELETE CASCADE,
  material_id  INTEGER NOT NULL REFERENCES materiales(id) ON DELETE RESTRICT,
  cantidad     NUMERIC(14,2) NOT NULL DEFAULT 0,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (almacen_id, material_id)
);

-- Índices de soporte
CREATE INDEX IF NOT EXISTS idx_stock_almacen_material ON stock_almacen(material_id);
CREATE INDEX IF NOT EXISTS idx_stock_almacen_updated  ON stock_almacen(updated_at);

COMMIT;
