-- Asegura default en tecnicos.id según su tipo actual,
-- respetando si ya es IDENTITY o si ya tiene nextval(...)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
  col_type      text;
  col_default   text;
  is_ident      text;
BEGIN
  SELECT data_type, column_default, is_identity
  INTO col_type, col_default, is_ident
  FROM information_schema.columns
  WHERE table_schema='public'
    AND table_name='tecnicos'
    AND column_name='id';

  IF col_type IS NULL THEN
    RAISE NOTICE 'No existe tecnicos.id; se omite.';
    RETURN;
  END IF;

  -- Si ya es identity, no tocar.
  IF is_ident = 'YES' THEN
    RAISE NOTICE 'tecnicos.id ya es IDENTITY; no se modifica.';
    RETURN;
  END IF;

  -- Si ya tiene default (incluye nextval), no tocar.
  IF col_default IS NOT NULL THEN
    RAISE NOTICE 'tecnicos.id ya tiene DEFAULT (%); no se modifica.', col_default;
    RETURN;
  END IF;

  IF col_type IN ('integer','bigint') THEN
    -- Si no es identity y no tiene default, lo convertimos a IDENTITY.
    EXECUTE 'ALTER TABLE tecnicos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
    RAISE NOTICE 'tecnicos.id ahora es IDENTITY.';
  ELSIF col_type = 'uuid' THEN
    -- Para UUID, usar gen_random_uuid()
    EXECUTE 'ALTER TABLE tecnicos ALTER COLUMN id SET DEFAULT gen_random_uuid()';
    RAISE NOTICE 'tecnicos.id ahora tiene DEFAULT gen_random_uuid().';
  ELSE
    RAISE NOTICE 'Tipo no soportado (%) para tecnicos.id; no se modifica el default.', col_type;
  END IF;
END$$;
