import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1758483929082 implements MigrationInterface {
    name = 'InitSchema1758483929082'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_municipio_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_ciudad_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_barrio_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "fk_orden_usuario"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "fk_orden_venta"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "fk_orden_tecnico"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "fk_ordenes_tecnico"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "fk_ordenes_ventas"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "fk_ordenes_usuarios"`);
        await queryRunner.query(`ALTER TABLE "evidencias" DROP CONSTRAINT "fk_evidencias_ordenes"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "orden_materiales_material_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "orden_materiales_orden_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "fk_inv_tecnico_material"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "fk_inv_tecnico_tecnico"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "inv_tecnico_material_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "inv_tecnico_tecnico_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sectores" DROP CONSTRAINT "sectores_municipio_codigo_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ventas_codigo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_busqueda"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_barrio"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tecnicos_nombre_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tecnicos_codigo_trgm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_smartolt_request"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_tipo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ordenes_estado"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ordenes_agendado_para"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ordenes_tecnico_estado"`);
        await queryRunner.query(`DROP INDEX "public"."ux_ordenes_codigo"`);
        await queryRunner.query(`DROP INDEX "public"."ux_ordenes_instal_por_venta"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_tecnico"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_codigo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_estado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_agenda"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ordenes_agendado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_evidencias_orden"`);
        await queryRunner.query(`DROP INDEX "public"."idx_evidencias_orden_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_evidencias_tipo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_om_orden"`);
        await queryRunner.query(`DROP INDEX "public"."idx_om_material"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orden_mat_orden"`);
        await queryRunner.query(`DROP INDEX "public"."ix_orden_materiales_orden"`);
        await queryRunner.query(`DROP INDEX "public"."ix_materiales_activo"`);
        await queryRunner.query(`DROP INDEX "public"."ix_materiales_nombre"`);
        await queryRunner.query(`DROP INDEX "public"."ux_inv_tecnico_tecmat"`);
        await queryRunner.query(`DROP INDEX "public"."ux_vias_codigo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sectores_nombre"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sectores_municipio_codigo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_municipios_codigo"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_tipo_cliente_check"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_estado_check"`);
        await queryRunner.query(`ALTER TABLE "planes" DROP CONSTRAINT "planes_tipo_check"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "chk_ordenes_estado_valido"`);
        await queryRunner.query(`ALTER TABLE "evidencias" DROP CONSTRAINT "chk_evidencias_tipo"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "om_qty_chk"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "om_pu_chk"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "orden_material_cantidad_chk"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "orden_material_precio_chk"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "ck_inv_tecnico_cantidad_nonneg"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "chk_inv_tecnico_cantidad_nn"`);
        await queryRunner.query(`ALTER TABLE "sectores" DROP CONSTRAINT "sectores_zona_check"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "inv_tecnico_tecnico_id_material_id_key"`);
        await queryRunner.query(`ALTER TABLE "sectores" DROP CONSTRAINT "uniq_sectores_mun_zona_nombre"`);
        await queryRunner.query(`CREATE TABLE "orden_cierres_idem" ("id" SERIAL NOT NULL, "orden_codigo" character varying(32) NOT NULL, "payload_hash" character varying(64) NOT NULL, "idempotency_key" character varying(128), "first_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "response_status" integer, "response_body" jsonb, CONSTRAINT "PK_cac2a1d36659e270a31a42be423" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_814583e3af729c9ac5da5e7b1f" ON "orden_cierres_idem" ("idempotency_key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5072fbd7a1300b1b92deb33a08" ON "orden_cierres_idem" ("orden_codigo", "payload_hash") `);
        await queryRunner.query(`CREATE TABLE "catalogo_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text, "nombre" text NOT NULL, "activo" boolean NOT NULL DEFAULT true, "orden" smallint, "meta" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "catalogo_id" uuid, CONSTRAINT "PK_8181cd85c9a0549622d3531bbc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2bd0b3fee63f625763c2e0dca" ON "catalogo_items" ("catalogo_id", "codigo") `);
        await queryRunner.query(`CREATE TABLE "catalogos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text NOT NULL, "descripcion" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8d2f3ffdd25acfdd036d9f9c89f" UNIQUE ("codigo"), CONSTRAINT "PK_1d78e1f35ded834637978e7cbf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "plan_alta"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "plan_mensual"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "recibo_img_key"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "cedula_img_key"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "firma_img_key"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "barrio_id"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "ciudad_id"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "geolat"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "geolng"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "municipio_id"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "zona"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "barrio_conjunto"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "via"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "nombre_via"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "indicador"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "orientacion"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "numero_casa"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "saldo"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "correo"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "barrio"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" DROP COLUMN "zona"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" DROP COLUMN "activo"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "metodo"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "payload_redacted"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "status_code"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "response_trunc"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "error_text"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "retry_count"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "correlacion"`);
        await queryRunner.query(`ALTER TABLE "planes" DROP COLUMN "velocidad_mbps"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "venta_id"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "usuario_id"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "lat"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "lng"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "onu_serial"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "vlan"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "precinto"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "cerrada_por"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "agendado_para"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "cierre_notas"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "codigoCliente"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "contexto"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "notas"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "cargos"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "creadoEn"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "actualizadoEn"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "turno"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "precio_unitario"`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "unidad"`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "activo"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "cargoadicional"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ADD "telefono" text`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "request_payload" jsonb`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "response_code" integer`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "response_body" jsonb`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "error" text`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "iniciada_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "firma_key" text`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "pdf_url" text`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "pdf_key" text`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "cierre_token" uuid`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "form_data" jsonb`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "precio_unitario" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "total_calculado" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "instalacion" numeric NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "mensualidad" numeric NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "cargoAdicional" numeric NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "creadoEn" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "ventas_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "usuario_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "plan_codigo"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "plan_codigo" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "plan_nombre"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "plan_nombre" character varying(120) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "alta_costo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "mensual_internet" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "mensual_tv" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "mensual_total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "recibo_pdf_key"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "recibo_pdf_key" character varying`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "contrato_pdf_key"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "contrato_pdf_key" character varying`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "tipo_cliente"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "tipo_cliente" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_documento_key"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "telefono" character varying`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_estado"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "estado" "public"."usuario_estado" NOT NULL DEFAULT 'nuevo'`);
        await queryRunner.query(`ALTER TABLE "tecnicos" DROP CONSTRAINT "tecnicos_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ADD "codigo" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ADD CONSTRAINT "UQ_b41ede5014b9012fd7b2193b15e" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ALTER COLUMN "nombre" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ALTER COLUMN "endpoint" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "request_id"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "request_id" text`);
        await queryRunner.query(`ALTER TABLE "planes" DROP CONSTRAINT "uq_planes_codigo"`);
        await queryRunner.query(`ALTER TABLE "planes" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "planes" ADD "codigo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "planes" ADD CONSTRAINT "UQ_f255684b3d2b750ac6788c5ab98" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "planes" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "planes" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "planes" ALTER COLUMN "vel_mbps" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "ordenes_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "codigo" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "estado" text NOT NULL DEFAULT 'agendada'`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "tipo" text`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "material_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ALTER COLUMN "cantidad" TYPE numeric(12,3)`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ALTER COLUMN "cantidad" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "material_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "cantidad"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "cantidad" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP CONSTRAINT "materiales_pkey"`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD CONSTRAINT "PK_bdb2febb21ca2abcdd52ec12559" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP CONSTRAINT "materiales_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "codigo" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "nombre" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD CONSTRAINT "UQ_7fa98a683ce81de255c3bf2d26a" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "materiales" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD "material_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ALTER COLUMN "cantidad" TYPE numeric(12,3)`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP CONSTRAINT "config_cargos_pkey"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD CONSTRAINT "PK_6bb3c3cc144d09d47a32b5bb491" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ALTER COLUMN "recontratacion" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ALTER COLUMN "recontratacion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vias" DROP CONSTRAINT "vias_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "sectores" ALTER COLUMN "zona" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "municipios" DROP CONSTRAINT "municipios_codigo_key"`);
        await queryRunner.query(`ALTER TABLE "municipios" DROP CONSTRAINT "municipios_nombre_key"`);
        await queryRunner.query(`ALTER TABLE "municipios" ALTER COLUMN "activo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_users" DROP CONSTRAINT "app_users_username_key"`);
        await queryRunner.query(`ALTER TABLE "app_users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "app_users" ADD "username" character varying(80) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_estado" ON "usuarios" ("estado") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_12fab9892d22718370d6dccf6d" ON "ordenes" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_e66a559ea34d60d39bf0f16b6f" ON "ordenes" ("estado") `);
        await queryRunner.query(`CREATE INDEX "IDX_11ee5476fd4f40aeac06660adf" ON "ordenes" ("tecnico_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eca538e4af115ad2b8f0292573" ON "orden_materiales" ("orden_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f19fb7422f45e7269944bc415" ON "orden_materiales" ("material_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_orden_materiales_orden_mat" ON "orden_materiales" ("orden_id", "material_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_materiales_codigo" ON "materiales" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_003ee7bf976605547308b3d58b" ON "inv_tecnico" ("tecnico_id", "material_id") `);
        await queryRunner.query(`CREATE INDEX "ix_inv_tecnico_tecnico" ON "inv_tecnico" ("tecnico_id") `);
        await queryRunner.query(`CREATE INDEX "ix_inv_tecnico_material" ON "inv_tecnico" ("material_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d69a8b13b58fcfa4a03dcc738b" ON "vias" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a6ea126337a50ff6015bfecc5" ON "vias" ("nombre") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd19774e0d20316832704b857f" ON "sectores" ("municipio_codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c17841acc4939a08f19c52a57" ON "sectores" ("zona") `);
        await queryRunner.query(`CREATE INDEX "IDX_d46fcb1f01d3037310b7594acb" ON "sectores" ("nombre") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca61f54e17be66859316ac5d87" ON "municipios" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa8405c6457229608b11ba1460" ON "municipios" ("nombre") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5d67cc2e38c80255e768c2b76a" ON "app_users" ("username") `);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "inv_tecnico_tecnico_id_material_id_key" UNIQUE ("tecnico_id", "material_id")`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "FK_eca538e4af115ad2b8f02925731" FOREIGN KEY ("orden_id") REFERENCES "ordenes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "FK_c33ac7cde98755d25f0905c641e" FOREIGN KEY ("tecnico_id") REFERENCES "tecnicos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "FK_bd07979d0f4a7392f0971ae8c25" FOREIGN KEY ("material_id") REFERENCES "materiales"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalogo_items" ADD CONSTRAINT "FK_c6775a06bda18c043cf5163791f" FOREIGN KEY ("catalogo_id") REFERENCES "catalogos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "catalogo_items" DROP CONSTRAINT "FK_c6775a06bda18c043cf5163791f"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "FK_bd07979d0f4a7392f0971ae8c25"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "FK_c33ac7cde98755d25f0905c641e"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "FK_eca538e4af115ad2b8f02925731"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "inv_tecnico_tecnico_id_material_id_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d67cc2e38c80255e768c2b76a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa8405c6457229608b11ba1460"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca61f54e17be66859316ac5d87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d46fcb1f01d3037310b7594acb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c17841acc4939a08f19c52a57"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd19774e0d20316832704b857f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a6ea126337a50ff6015bfecc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d69a8b13b58fcfa4a03dcc738b"`);
        await queryRunner.query(`DROP INDEX "public"."ix_inv_tecnico_material"`);
        await queryRunner.query(`DROP INDEX "public"."ix_inv_tecnico_tecnico"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_003ee7bf976605547308b3d58b"`);
        await queryRunner.query(`DROP INDEX "public"."ux_materiales_codigo"`);
        await queryRunner.query(`DROP INDEX "public"."ux_orden_materiales_orden_mat"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f19fb7422f45e7269944bc415"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eca538e4af115ad2b8f0292573"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11ee5476fd4f40aeac06660adf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e66a559ea34d60d39bf0f16b6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12fab9892d22718370d6dccf6d"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_estado"`);
        await queryRunner.query(`ALTER TABLE "app_users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "app_users" ADD "username" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_users" ADD CONSTRAINT "app_users_username_key" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "municipios" ALTER COLUMN "activo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "municipios" ADD CONSTRAINT "municipios_nombre_key" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "municipios" ADD CONSTRAINT "municipios_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "sectores" ALTER COLUMN "zona" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vias" ADD CONSTRAINT "vias_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ALTER COLUMN "recontratacion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ALTER COLUMN "recontratacion" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP CONSTRAINT "PK_6bb3c3cc144d09d47a32b5bb491"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "id" smallint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD CONSTRAINT "config_cargos_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ALTER COLUMN "cantidad" TYPE numeric(14,3)`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD "material_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP CONSTRAINT "UQ_7fa98a683ce81de255c3bf2d26a"`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "nombre" character varying(120) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "codigo" character varying(32)`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD CONSTRAINT "materiales_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP CONSTRAINT "PK_bdb2febb21ca2abcdd52ec12559"`);
        await queryRunner.query(`ALTER TABLE "materiales" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD CONSTRAINT "materiales_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "cantidad"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "cantidad" numeric(14,3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "material_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ALTER COLUMN "cantidad" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ALTER COLUMN "cantidad" TYPE numeric(14,3)`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "material_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "tipo" character varying(30) NOT NULL DEFAULT 'instalacion'`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "estado" character varying(20) NOT NULL DEFAULT 'pendiente'`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "codigo" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "ordenes_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "planes" ALTER COLUMN "vel_mbps" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "planes" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "planes" ADD "nombre" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "planes" DROP CONSTRAINT "UQ_f255684b3d2b750ac6788c5ab98"`);
        await queryRunner.query(`ALTER TABLE "planes" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "planes" ADD "codigo" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "planes" ADD CONSTRAINT "uq_planes_codigo" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "request_id"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "request_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ALTER COLUMN "endpoint" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ALTER COLUMN "nombre" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tecnicos" DROP CONSTRAINT "UQ_b41ede5014b9012fd7b2193b15e"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ADD "codigo" character varying(32) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ADD CONSTRAINT "tecnicos_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "estado" text NOT NULL DEFAULT 'nuevo'`);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_estado" ON "usuarios" ("estado") `);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "telefono" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "email" character varying(160)`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_documento_key" UNIQUE ("documento")`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "tipo_cliente"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "tipo_cliente" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "contrato_pdf_key"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "contrato_pdf_key" text`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "recibo_pdf_key"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "recibo_pdf_key" text`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "mensual_total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "mensual_tv" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "mensual_internet" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "alta_costo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "plan_nombre"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "plan_nombre" text`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "plan_codigo"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "plan_codigo" text`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "usuario_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "ventas_codigo_key" UNIQUE ("codigo")`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "actualizadoEn"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "creadoEn"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "cargoAdicional"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "mensualidad"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" DROP COLUMN "instalacion"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "total_calculado"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "precio_unitario"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "form_data"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "cierre_token"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "pdf_key"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "pdf_url"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "firma_key"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP COLUMN "iniciada_at"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "error"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "response_body"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "response_code"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "request_payload"`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tecnicos" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "config_cargos" ADD "cargoadicional" numeric(12,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "activo" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "materiales" ADD "unidad" character varying(16) DEFAULT 'UND'`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "precio_unitario" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "turno" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "actualizadoEn" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "creadoEn" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "cargos" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "notas" text`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "contexto" jsonb`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "codigoCliente" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "cierre_notas" text`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "agendado_para" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "cerrada_por" character varying(80)`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "precinto" character varying(40)`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "vlan" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "onu_serial" character varying(40)`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "lng" double precision`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "lat" double precision`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "usuario_id" uuid`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD "venta_id" uuid`);
        await queryRunner.query(`ALTER TABLE "planes" ADD "velocidad_mbps" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "correlacion" text`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "retry_count" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "error_text" text`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "response_trunc" jsonb`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "status_code" integer`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "payload_redacted" jsonb`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "smartolt_logs" ADD "metodo" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ADD "activo" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "tecnicos" ADD "zona" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "barrio" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "correo" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "saldo" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "numero_casa" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "orientacion" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "indicador" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "nombre_via" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "via" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "barrio_conjunto" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "zona" text`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "municipio_id" uuid`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "geolng" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "geolat" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "ciudad_id" uuid`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "barrio_id" uuid`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "direccion" text`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "firma_img_key" text`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "cedula_img_key" text`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "recibo_img_key" text`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "plan_mensual" numeric(12,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "plan_alta" numeric(12,2) DEFAULT '0'`);
        await queryRunner.query(`DROP TABLE "catalogos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2bd0b3fee63f625763c2e0dca"`);
        await queryRunner.query(`DROP TABLE "catalogo_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5072fbd7a1300b1b92deb33a08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_814583e3af729c9ac5da5e7b1f"`);
        await queryRunner.query(`DROP TABLE "orden_cierres_idem"`);
        await queryRunner.query(`ALTER TABLE "sectores" ADD CONSTRAINT "uniq_sectores_mun_zona_nombre" UNIQUE ("municipio_codigo", "zona", "nombre")`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "inv_tecnico_tecnico_id_material_id_key" UNIQUE ("tecnico_id", "material_id")`);
        await queryRunner.query(`ALTER TABLE "sectores" ADD CONSTRAINT "sectores_zona_check" CHECK ((zona = ANY (ARRAY['BARRIO'::text, 'CONJUNTO'::text, 'COMUNA'::text])))`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "chk_inv_tecnico_cantidad_nn" CHECK ((cantidad >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "ck_inv_tecnico_cantidad_nonneg" CHECK ((cantidad >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "orden_material_precio_chk" CHECK ((precio_unitario >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "orden_material_cantidad_chk" CHECK ((cantidad >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "om_pu_chk" CHECK ((precio_unitario >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "om_qty_chk" CHECK ((cantidad > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "evidencias" ADD CONSTRAINT "chk_evidencias_tipo" CHECK (((tipo)::text = ANY ((ARRAY['foto'::character varying, 'firma'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "chk_ordenes_estado_valido" CHECK (((estado)::text = ANY ((ARRAY['creada'::character varying, 'agendada'::character varying, 'cerrada'::character varying, 'cancelada'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "planes" ADD CONSTRAINT "planes_tipo_check" CHECK ((tipo = ANY (ARRAY['internet'::text, 'tv'::text])))`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_estado_check" CHECK ((estado = ANY (ARRAY['nuevo'::text, 'contratado'::text, 'instalado'::text, 'desconectado'::text, 'terminado'::text])))`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_tipo_cliente_check" CHECK ((tipo_cliente = ANY (ARRAY['hogar'::text, 'corporativo'::text])))`);
        await queryRunner.query(`CREATE INDEX "idx_municipios_codigo" ON "municipios" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "idx_sectores_municipio_codigo" ON "sectores" ("municipio_codigo") `);
        await queryRunner.query(`CREATE INDEX "idx_sectores_nombre" ON "sectores" ("nombre") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_vias_codigo" ON "vias" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_inv_tecnico_tecmat" ON "inv_tecnico" ("tecnico_id", "material_id") `);
        await queryRunner.query(`CREATE INDEX "ix_materiales_nombre" ON "materiales" ("nombre") `);
        await queryRunner.query(`CREATE INDEX "ix_materiales_activo" ON "materiales" ("activo") `);
        await queryRunner.query(`CREATE INDEX "ix_orden_materiales_orden" ON "orden_materiales" ("orden_id") `);
        await queryRunner.query(`CREATE INDEX "idx_orden_mat_orden" ON "orden_materiales" ("orden_id") `);
        await queryRunner.query(`CREATE INDEX "idx_om_material" ON "orden_materiales" ("material_id") `);
        await queryRunner.query(`CREATE INDEX "idx_om_orden" ON "orden_materiales" ("orden_id") `);
        await queryRunner.query(`CREATE INDEX "idx_evidencias_tipo" ON "evidencias" ("tipo") `);
        await queryRunner.query(`CREATE INDEX "idx_evidencias_orden_id" ON "evidencias" ("orden_id") `);
        await queryRunner.query(`CREATE INDEX "idx_evidencias_orden" ON "evidencias" ("orden_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_agendado" ON "ordenes" ("agendado_para") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_agenda" ON "ordenes" ("agendado_para") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_estado" ON "ordenes" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_codigo" ON "ordenes" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_tecnico" ON "ordenes" ("tecnico_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_usuario" ON "ordenes" ("usuario_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_ordenes_instal_por_venta" ON "ordenes" ("venta_id") WHERE ((tipo)::text = 'INSTALACION'::text)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_ordenes_codigo" ON "ordenes" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "ix_ordenes_tecnico_estado" ON "ordenes" ("estado", "tecnico_id") `);
        await queryRunner.query(`CREATE INDEX "ix_ordenes_agendado_para" ON "ordenes" ("agendado_para") `);
        await queryRunner.query(`CREATE INDEX "ix_ordenes_estado" ON "ordenes" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_created_at" ON "ordenes" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ordenes_tipo" ON "ordenes" ("tipo") `);
        await queryRunner.query(`CREATE INDEX "idx_smartolt_request" ON "smartolt_logs" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tecnicos_codigo_trgm" ON "tecnicos" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "idx_tecnicos_nombre_trgm" ON "tecnicos" ("nombre") `);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_barrio" ON "usuarios" ("barrio") `);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_busqueda" ON "usuarios" ("codigo", "apellido", "documento") `);
        await queryRunner.query(`CREATE INDEX "idx_ventas_codigo" ON "ventas" ("codigo") `);
        await queryRunner.query(`ALTER TABLE "sectores" ADD CONSTRAINT "sectores_municipio_codigo_fkey" FOREIGN KEY ("municipio_codigo") REFERENCES "municipios"("codigo") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "inv_tecnico_tecnico_id_fkey" FOREIGN KEY ("tecnico_id") REFERENCES "tecnicos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "inv_tecnico_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "materiales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "fk_inv_tecnico_tecnico" FOREIGN KEY ("tecnico_id") REFERENCES "tecnicos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "fk_inv_tecnico_material" FOREIGN KEY ("material_id") REFERENCES "materiales"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "orden_materiales_orden_id_fkey" FOREIGN KEY ("orden_id") REFERENCES "ordenes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "orden_materiales_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "materiales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidencias" ADD CONSTRAINT "fk_evidencias_ordenes" FOREIGN KEY ("orden_id") REFERENCES "ordenes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "fk_ordenes_usuarios" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "fk_ordenes_ventas" FOREIGN KEY ("venta_id") REFERENCES "ventas"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "fk_ordenes_tecnico" FOREIGN KEY ("tecnico_id") REFERENCES "tecnicos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "fk_orden_tecnico" FOREIGN KEY ("tecnico_id") REFERENCES "tecnicos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "fk_orden_venta" FOREIGN KEY ("venta_id") REFERENCES "ventas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "fk_orden_usuario" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_barrio_id_fkey" FOREIGN KEY ("barrio_id") REFERENCES "barrios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_ciudad_id_fkey" FOREIGN KEY ("ciudad_id") REFERENCES "ciudades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_municipio_id_fkey" FOREIGN KEY ("municipio_id") REFERENCES "municipios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
