import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1758484018068 implements MigrationInterface {
    name = 'InitSchema1758484018068'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "ventas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying(20) NOT NULL, "cliente_nombre" character varying(120) NOT NULL, "cliente_apellido" character varying(120) NOT NULL, "documento" character varying(30) NOT NULL, "usuario_id" uuid NOT NULL, "estado" character varying(20) NOT NULL DEFAULT 'creada', "plan_codigo" character varying(20) NOT NULL, "plan_nombre" character varying(120) NOT NULL, "plan_vel_mbps" integer, "alta_costo" numeric(12,2) NOT NULL DEFAULT '0', "mensual_internet" numeric(12,2) NOT NULL DEFAULT '0', "mensual_tv" numeric(12,2) NOT NULL DEFAULT '0', "mensual_total" numeric(12,2) NOT NULL DEFAULT '0', "incluye_tv" boolean NOT NULL DEFAULT false, "total" numeric(12,2) NOT NULL DEFAULT '0', "recibo_pdf_key" character varying, "contrato_pdf_key" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b8b73abe8561829c019531d9a2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."usuario_estado" AS ENUM('nuevo', 'contratado', 'instalado', 'desconectado', 'terminado')`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying(20) NOT NULL, "tipo_cliente" character varying NOT NULL, "nombre" character varying(120) NOT NULL, "apellido" character varying(120) NOT NULL, "documento" character varying(30) NOT NULL, "email" character varying, "telefono" character varying, "estado" "public"."usuario_estado" NOT NULL DEFAULT 'nuevo', CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_estado" ON "usuarios" ("estado") `);
        await queryRunner.query(`CREATE TABLE "tecnicos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text, "telefono" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b41ede5014b9012fd7b2193b15e" UNIQUE ("codigo"), CONSTRAINT "PK_57a82263172b130f3dafce11faa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "smartolt_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "endpoint" text, "request_payload" jsonb, "response_code" integer, "response_body" jsonb, "error" text, "request_id" text, CONSTRAINT "PK_391e78ee98bda31fd2a09c4411e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "planes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying NOT NULL, "nombre" character varying NOT NULL, "vel_mbps" integer NOT NULL, "alta_costo" numeric(12,2) NOT NULL DEFAULT '0', "mensual" numeric(12,2) NOT NULL DEFAULT '0', "activo" boolean NOT NULL DEFAULT true, "tipo" text NOT NULL DEFAULT 'internet', CONSTRAINT "UQ_f255684b3d2b750ac6788c5ab98" UNIQUE ("codigo"), CONSTRAINT "PK_91be19f449ba03767fe51acdebc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ordenes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "estado" text NOT NULL DEFAULT 'agendada', "tecnico_id" uuid, "iniciada_at" TIMESTAMP WITH TIME ZONE, "cerrada_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "firma_key" text, "pdf_url" text, "pdf_key" text, "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL DEFAULT '0', "cierre_token" uuid, "tipo" text, "form_data" jsonb, CONSTRAINT "PK_58713affeb8e3b7b30b9eeeee7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_12fab9892d22718370d6dccf6d" ON "ordenes" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_e66a559ea34d60d39bf0f16b6f" ON "ordenes" ("estado") `);
        await queryRunner.query(`CREATE INDEX "IDX_11ee5476fd4f40aeac06660adf" ON "ordenes" ("tecnico_id") `);
        await queryRunner.query(`CREATE TABLE "evidencias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orden_id" uuid NOT NULL, "tipo" character varying(16) NOT NULL, "object_key" character varying(255) NOT NULL, "mime" character varying(80), "size" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c2e2ff397deaf434b623ed20507" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orden_materiales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orden_id" uuid NOT NULL, "material_id" integer NOT NULL, "cantidad" numeric(12,3) NOT NULL DEFAULT '0', "precio_unitario" numeric(12,2) NOT NULL DEFAULT '0', "total_calculado" numeric(14,2), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8fc75b2925fd0a02880631e033b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eca538e4af115ad2b8f0292573" ON "orden_materiales" ("orden_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f19fb7422f45e7269944bc415" ON "orden_materiales" ("material_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_orden_materiales_orden_mat" ON "orden_materiales" ("orden_id", "material_id") `);
        await queryRunner.query(`CREATE TABLE "orden_cierres_idem" ("id" SERIAL NOT NULL, "orden_codigo" character varying(32) NOT NULL, "payload_hash" character varying(64) NOT NULL, "idempotency_key" character varying(128), "first_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "response_status" integer, "response_body" jsonb, CONSTRAINT "PK_cac2a1d36659e270a31a42be423" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_814583e3af729c9ac5da5e7b1f" ON "orden_cierres_idem" ("idempotency_key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5072fbd7a1300b1b92deb33a08" ON "orden_cierres_idem" ("orden_codigo", "payload_hash") `);
        await queryRunner.query(`CREATE TABLE "materiales" ("id" SERIAL NOT NULL, "codigo" text NOT NULL, "nombre" text NOT NULL, "precio" numeric(12,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7fa98a683ce81de255c3bf2d26a" UNIQUE ("nombre"), CONSTRAINT "PK_bdb2febb21ca2abcdd52ec12559" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_materiales_codigo" ON "materiales" ("codigo") `);
        await queryRunner.query(`CREATE TABLE "inv_tecnico" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tecnico_id" uuid NOT NULL, "material_id" integer NOT NULL, "cantidad" numeric(12,3) NOT NULL DEFAULT '0', CONSTRAINT "PK_e58555e9ede4f85a4c9c5507bd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_003ee7bf976605547308b3d58b" ON "inv_tecnico" ("tecnico_id", "material_id") `);
        await queryRunner.query(`CREATE TABLE "config_cargos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recontratacion" numeric NOT NULL DEFAULT '0', "instalacion" numeric NOT NULL DEFAULT '0', "mensualidad" numeric NOT NULL DEFAULT '0', "cargoAdicional" numeric NOT NULL DEFAULT '0', "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6bb3c3cc144d09d47a32b5bb491" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4d3096c822e57784a81ea79b71c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d69a8b13b58fcfa4a03dcc738b" ON "vias" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a6ea126337a50ff6015bfecc5" ON "vias" ("nombre") `);
        await queryRunner.query(`CREATE TABLE "sectores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "municipio_codigo" text NOT NULL, "zona" text, "nombre" text NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_e4690b445beae51b850640e7d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd19774e0d20316832704b857f" ON "sectores" ("municipio_codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c17841acc4939a08f19c52a57" ON "sectores" ("zona") `);
        await queryRunner.query(`CREATE INDEX "IDX_d46fcb1f01d3037310b7594acb" ON "sectores" ("nombre") `);
        await queryRunner.query(`CREATE TABLE "municipios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_10d04b4b4e39ba40240b61e919d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca61f54e17be66859316ac5d87" ON "municipios" ("codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa8405c6457229608b11ba1460" ON "municipios" ("nombre") `);
        await queryRunner.query(`CREATE TABLE "catalogo_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text, "nombre" text NOT NULL, "activo" boolean NOT NULL DEFAULT true, "orden" smallint, "meta" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "catalogo_id" uuid, CONSTRAINT "PK_8181cd85c9a0549622d3531bbc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2bd0b3fee63f625763c2e0dca" ON "catalogo_items" ("catalogo_id", "codigo") `);
        await queryRunner.query(`CREATE TABLE "catalogos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text NOT NULL, "descripcion" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8d2f3ffdd25acfdd036d9f9c89f" UNIQUE ("codigo"), CONSTRAINT "PK_1d78e1f35ded834637978e7cbf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "app_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(80) NOT NULL, "pass_hash" text NOT NULL, "roles" text array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9b97e4fbff9c2f3918fda27f999" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5d67cc2e38c80255e768c2b76a" ON "app_users" ("username") `);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "precio_unitario"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "total_calculado"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "precio_unitario" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "total_calculado" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."ux_orden_materiales_orden_mat"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f19fb7422f45e7269944bc415"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "material_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "cantidad"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "cantidad" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ALTER COLUMN "cantidad" TYPE numeric(14,3)`);
        await queryRunner.query(`CREATE INDEX "IDX_8f19fb7422f45e7269944bc415" ON "orden_materiales" ("material_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_orden_materiales_orden_mat" ON "orden_materiales" ("orden_id", "material_id") `);
        await queryRunner.query(`CREATE INDEX "ix_inv_tecnico_tecnico" ON "inv_tecnico" ("tecnico_id") `);
        await queryRunner.query(`CREATE INDEX "ix_inv_tecnico_material" ON "inv_tecnico" ("material_id") `);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "inv_tecnico_tecnico_id_material_id_key" UNIQUE ("tecnico_id", "material_id")`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD CONSTRAINT "FK_eca538e4af115ad2b8f02925731" FOREIGN KEY ("orden_id") REFERENCES "ordenes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "FK_c33ac7cde98755d25f0905c641e" FOREIGN KEY ("tecnico_id") REFERENCES "tecnicos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ADD CONSTRAINT "FK_bd07979d0f4a7392f0971ae8c25" FOREIGN KEY ("material_id") REFERENCES "materiales"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalogo_items" ADD CONSTRAINT "FK_c6775a06bda18c043cf5163791f" FOREIGN KEY ("catalogo_id") REFERENCES "catalogos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "catalogo_items" DROP CONSTRAINT "FK_c6775a06bda18c043cf5163791f"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "FK_bd07979d0f4a7392f0971ae8c25"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "FK_c33ac7cde98755d25f0905c641e"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP CONSTRAINT "FK_eca538e4af115ad2b8f02925731"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" DROP CONSTRAINT "inv_tecnico_tecnico_id_material_id_key"`);
        await queryRunner.query(`DROP INDEX "public"."ix_inv_tecnico_material"`);
        await queryRunner.query(`DROP INDEX "public"."ix_inv_tecnico_tecnico"`);
        await queryRunner.query(`DROP INDEX "public"."ux_orden_materiales_orden_mat"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f19fb7422f45e7269944bc415"`);
        await queryRunner.query(`ALTER TABLE "inv_tecnico" ALTER COLUMN "cantidad" TYPE numeric(12,3)`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "cantidad"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "cantidad" numeric(12,3) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "material_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8f19fb7422f45e7269944bc415" ON "orden_materiales" ("material_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_orden_materiales_orden_mat" ON "orden_materiales" ("orden_id", "material_id") `);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "total_calculado"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" DROP COLUMN "precio_unitario"`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "total_calculado" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "orden_materiales" ADD "precio_unitario" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d67cc2e38c80255e768c2b76a"`);
        await queryRunner.query(`DROP TABLE "app_users"`);
        await queryRunner.query(`DROP TABLE "catalogos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2bd0b3fee63f625763c2e0dca"`);
        await queryRunner.query(`DROP TABLE "catalogo_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa8405c6457229608b11ba1460"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca61f54e17be66859316ac5d87"`);
        await queryRunner.query(`DROP TABLE "municipios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d46fcb1f01d3037310b7594acb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c17841acc4939a08f19c52a57"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd19774e0d20316832704b857f"`);
        await queryRunner.query(`DROP TABLE "sectores"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a6ea126337a50ff6015bfecc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d69a8b13b58fcfa4a03dcc738b"`);
        await queryRunner.query(`DROP TABLE "vias"`);
        await queryRunner.query(`DROP TABLE "config_cargos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_003ee7bf976605547308b3d58b"`);
        await queryRunner.query(`DROP TABLE "inv_tecnico"`);
        await queryRunner.query(`DROP INDEX "public"."ux_materiales_codigo"`);
        await queryRunner.query(`DROP TABLE "materiales"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5072fbd7a1300b1b92deb33a08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_814583e3af729c9ac5da5e7b1f"`);
        await queryRunner.query(`DROP TABLE "orden_cierres_idem"`);
        await queryRunner.query(`DROP INDEX "public"."ux_orden_materiales_orden_mat"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f19fb7422f45e7269944bc415"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eca538e4af115ad2b8f0292573"`);
        await queryRunner.query(`DROP TABLE "orden_materiales"`);
        await queryRunner.query(`DROP TABLE "evidencias"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11ee5476fd4f40aeac06660adf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e66a559ea34d60d39bf0f16b6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12fab9892d22718370d6dccf6d"`);
        await queryRunner.query(`DROP TABLE "ordenes"`);
        await queryRunner.query(`DROP TABLE "planes"`);
        await queryRunner.query(`DROP TABLE "smartolt_logs"`);
        await queryRunner.query(`DROP TABLE "tecnicos"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_estado"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TYPE "public"."usuario_estado"`);
        await queryRunner.query(`DROP TABLE "ventas"`);
    }

}
